### ISSUE TITLE
How to change icon

### ISSUE THREAD

**Issue by Sparkmb21** [dahln/BlazorSpinner#5]
Any idea for the  change loading icon?

**Comment by dahln** [comment]
I have done some exploration on changing the loading icon something different. To simplify the spinner, the current loading icon is just svg code hard-coded into the component. But I could add a parament that could allow a developer-defined SVG to passed in.

**Comment by dahln** [comment]
Done. Review updated readme for how to customize the text or the icon. Note that there are breaking changes from v2 to v3.
